# -*- coding: utf-8 -*-
"""Копия блокнота "Добро пожаловать в Colaboratory!"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WHpFZvnb2_aNYqEp2arXC5PjyFE1g8Vz
"""

import pandas as pd

data = pd.read_csv('sample_data/california_housing_train.csv')

filtered_data = data[(data['population'] >= 0) & (data['population'] <= 500)]

average_house_price = filtered_data['median_house_value'].mean()

print(f"Средняя стоимость дома для населения от 0 до 500: ${average_house_price:.2f}")